services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      MONGO_INITDB_DATABASE: dreamtracker
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root-password
#    ports:
#      - '27017:27017'

  postgres:
    image: postgres:14.12-alpine
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: dreamtracker
      POSTGRES_ADMIN_PASSWORD: dev-admin-password
    ports:
      - '5432:5432'